spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.89.51.23:3306/DFP_IMAGE?useUnicode=true&characterEncoding=utf8&useSSL=false
    ##url: jdbc:mysql://10.0.55.82:3306/DFP_IMAGE?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      naming:
        ## 处理centos大小敏感的问题
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081
  servlet:
    context-path: /image


